### ISSUE TITLE
AVX2 check

### ISSUE THREAD

**Issue by aaronmcohen** [IBM-ICP4D/Install_Precheck_CPD_v3#1]
Please consider adding a check for AVX 2. Due to Tensorflow all the Watson Services need a CPU that supports AVX2. While AVX2 has been supported by modern CPUs for some time the old Broadwell processors are popular on Azure and Google Cloud.

**Comment by dhgaan-ibm** [comment]
Hi, this check has been added in recent commits! Please let us know if there are any issues
