### ISSUE TITLE
Precheck tool should enabled for AIRGAP environment. currently is failed in airgap environment

### ISSUE THREAD

**Issue by ekambaraml** [IBM-ICP4D/Install_Precheck_CPD_v3#7]
This tool has hard requirement of a python tool on a specific path and trying to download from internet.  This is not working on the AIRGAP environment.

Here is the logs

![image](https://user-images.githubusercontent.com/26153008/91629653-7ffbeb00-e990-11ea-80f5-10af58079a85.png)

**Comment by sanjitc** [comment]
Duplicate of https://github.com/IBM-ICP4D/Install_Precheck_CPD_v3/issues/6
